import type { InternalPage } from "@/components/admin/menu/state/useMenuStore";

/* =========================
 * eCommerce Internal Pages
 * ======================= */
export const ECOMMERCE_INTERNAL_PAGES: InternalPage[] = [
  // ===== CORE =====
  { id: "home", path: "/", label: "Home", labelVi: "Trang chủ" },
  { id: "login", path: "/login", label: "Login", labelVi: "Đăng nhập" },
  { id: "categories", path: "/categories", label: "Categories", labelVi: "Danh mục" },
  { id: "products", path: "/products", label: "Products", labelVi: "Sản phẩm" },
  { id: "collections", path: "/collections", label: "Collections", labelVi: "Bộ sưu tập" },
  { id: "new-arrivals", path: "/new", label: "New Arrivals", labelVi: "Hàng mới" },
  { id: "best-sellers", path: "/best-sellers", label: "Best Sellers", labelVi: "Bán chạy" },
  { id: "promotions", path: "/promotions", label: "Promotions", labelVi: "Khuyến mãi" },
  { id: "coupons", path: "/promotions/coupons", label: "Coupons", labelVi: "Mã giảm giá" },
  { id: "flash-sale", path: "/promotions/flash-sale", label: "Flash Sale", labelVi: "Flash Sale" },
  { id: "combos", path: "/promotions/combo", label: "Combos", labelVi: "Combo" },
  { id: "blog", path: "/blog", label: "Blog", labelVi: "Blog / Hướng dẫn" },
  { id: "guides", path: "/guides", label: "Buying Guides", labelVi: "Hướng dẫn mua hàng" },
  { id: "about", path: "/about-us", label: "About Us", labelVi: "Về chúng tôi" },
  { id: "support", path: "/support", label: "Support Center", labelVi: "Trung tâm hỗ trợ" },
  { id: "faq", path: "/support/faq", label: "FAQ", labelVi: "Câu hỏi thường gặp" },
  { id: "shipping", path: "/support/shipping", label: "Shipping Policy", labelVi: "Vận chuyển" },
  { id: "returns", path: "/support/returns", label: "Returns & Refunds", labelVi: "Đổi trả" },
  { id: "contact", path: "/contact", label: "Contact", labelVi: "Liên hệ" },
  { id: "account", path: "/account", label: "Account", labelVi: "Tài khoản" },
  { id: "orders", path: "/account/orders", label: "My Orders", labelVi: "Đơn hàng" },
  { id: "wishlist", path: "/account/wishlist", label: "Wishlist", labelVi: "Yêu thích" },
  { id: "cart", path: "/cart", label: "Cart", labelVi: "Giỏ hàng" },
  { id: "checkout", path: "/checkout", label: "Checkout", labelVi: "Thanh toán" },

  // ===== ADMIN =====
  { id: "admin", path: "/admin", label: "Dashboard", labelVi: "Dashboard" },
  { id: "pages", path: "/admin/pages", label: "Pages", labelVi: "Pages" },
  { id: "sections", path: "/admin/sections", label: "Sections", labelVi: "Sections" },
  { id: "Blocks", path: "/admin/blocks", label: "Blocks", labelVi: "Blocks" },
  { id: "Theme", path: "/admin/theme", label: "Theme", labelVi: "Theme" },
  { id: "assets", path: "/admin/assets", label: "Assets", labelVi: "Assets" },
  { id: "menu", path: "/admin/menu", label: "Menu", labelVi: "Menu" },
  { id: "integrations", path: "/admin/integrations", label: "integrations", labelVi: "Integrations" },
  { id: "product", path: "/admin/product", label: "Product", labelVi: "Product" },
  { id: "category", path: "/admin/category", label: "Category", labelVi: "Category" },
  { id: "variant", path: "/admin/variant", label: "Variant", labelVi: "Variant" },
  { id: "inventory", path: "/admin/inventory", label: "Inventory", labelVi: "Inventory" },
  { id: "stock-levels", path: "/admin/stock-levels", label: "Stock Levels", labelVi: "Stock Levels" },
  { id: "stock-movements", path: "/admin/stock-movements", label: "Stock Movements", labelVi: "Stock Movements" },
  { id: "purchase_orders", path: "/admin/purchase_orders", label: "Purchase Orders", labelVi: "Purchase Orders" },
  { id: "orders", path: "/admin/orders", label: "Orders", labelVi: "Orders" },
  { id: "payments", path: "/admin/payments", label: "Payments", labelVi: "Payments" },
  { id: "refunds", path: "/admin/refunds", label: "Refunds", labelVi: "Refunds" },
  { id: "customers", path: "/admin/customers", label: "Customers", labelVi: "Customers" },
  { id: "customers", path: "/admin/customer-manager", label: "Customer Manager", labelVi: "Customer Manager" },
  { id: "addresses", path: "/admin/addresses", label: "Addresses", labelVi: "Addresses" },
  { id: "email", path: "/admin/email", label: "Email", labelVi: "Email" },
  { id: "webhooks", path: "/admin/webhooks", label: "Webhooks", labelVi: "Webhooks" },
  { id: "storage", path: "/admin/storage", label: "Storage", labelVi: "Storage" },
  { id: "settings", path: "/admin/settings", label: "Settings", labelVi: "Settings" },
  { id: "store", path: "/admin/store", label: "Store", labelVi: "Store" },
  { id: "shipping", path: "/admin/shipping", label: "Shipping", labelVi: "Shipping" },
  { id: "taxes", path: "/admin/taxes", label: "Taxes", labelVi: "Taxes" },
  { id: "maintenance", path: "/admin/maintenance", label: "Maintenance", labelVi: "Maintenance" },
  { id: "logs", path: "/admin/logs", label: "Logs", labelVi: "Logs" },
  { id: "chat", path: "/admin/chat", label: "Chat", labelVi: "Chat" },
  { id: "bugs", path: "/admin/bugs", label: "Bugs", labelVi: "Bugs" },
];

/* =========================
 * eCommerce Internal HEADER
 * ======================= */
export const ECOMMERCE_HEADER_FULL = [
  "Home",
  "Login",
  "Categories",
  "Products",
  "Collections",
  "New Arrivals",
  "Best Sellers",
  "Promotions",
  "Coupons",
  "Flash Sale",
  "Combos",
  "Blog",
  "Buying Guides",
  "About Us",
  "Support Center",
  "FAQ",
  "Shipping Policy",
  "Returns & Refunds",
  "Contact",
  "Account",
  "My Orders",
  "Wishlist",
  "Cart",
  "Checkout",
] as const;

export const ECOMMERCE_ADMIN_FULL = [
  "Dashboard",
  "Pages",
  "Sections",
  "Blocks",
  "Theme",
  "Assets",
  "Menu",
  "Integrations",
  "Product",
  "Category",
  "Inventory",
  "Stock Levels",
  "Stock Movements",
  "Purchase Orders",
  "Orders",
  "Payments",
  "Refunds",
  "Customer",
  "Addresses",
  "integrations",
  "Payment",
  "Email",
  "Webhooks",
  "Storage",
  "Settings",
  "Store",
  "Shipping",
  "Taxes",
  "Maintenance",
  "Logs",
  "Chat",
] as const;
