import { WorkflowData } from './types';

export const CREATE_SITE_WORKFLOW: WorkflowData = {
    title: 'CREATE SITE WORKFLOW',
    subtitle: 'Automated site creation pipeline',
    groups: [
        {
            id: 'create',
            title: 'CREATE SITE',
            color: '#22c55e',
            nodes: [
                {
                    id: 'validate',
                    step: 1,
                    title: 'Validate Input',
                    subtitle: 'Validate request data',
                    description: 'Validate site creation payload and workspace information.',
                    icon: 'bi bi-shield-check',
                    color: 'blue',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/validate',
                    request: [
                        'name',
                        'domain',
                        'type',
                        'category',
                        'contactEmail',
                        'contactPhone',
                        'seoTitle',
                        'seoDescription',
                        'status',
                        'isPublic',
                        'publishedAt',
                        'workspaceId',
                    ],
                    response: [
                        'success',
                        'data.name',
                        'data.domain',
                        'data.type',
                        'data.workspaceId',
                    ],
                },
                {
                    id: 'check-domain',
                    step: 2,
                    title: 'Check Domain',
                    subtitle: 'Verify availability',
                    description: 'Check whether the submitted domain already exists.',
                    icon: 'bi bi-globe2',
                    color: 'green',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/check-domain',
                    request: ['domain'],
                    response: ['success', 'available', 'domain'],
                },
                {
                    id: 'create',
                    step: 3,
                    title: 'Create Site',
                    subtitle: 'Create database record',
                    description: 'Create the Site record and assign ownership to the current user.',
                    icon: 'bi bi-globe',
                    color: 'blue',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/create',
                    request: ['name', 'domain', 'type', 'category', 'workspaceId'],
                    response: ['success', 'data.siteId', 'data.site'],
                },
                {
                    id: 'system-pages',
                    step: 4,
                    title: 'Create System Pages',
                    subtitle: 'Header • Footer • 404',
                    description:
                        'Create the predefined system pages for the site before initializing menus and public pages.',
                    icon: 'bi bi-file-earmark',
                    color: 'blue',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/pages/system',
                    request: ['siteId'],
                    response: ['success', 'data.siteId', 'data.count', 'data.pages'],
                },
                {
                    id: 'assets',
                    step: 5,
                    title: 'Upload Assets',
                    subtitle: 'Logo • Favicon',
                    description:
                        'Upload the site logo and favicon into the site storage directory.',
                    icon: 'bi bi-cloud-arrow-up',
                    color: 'purple',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/assets',
                    request: ['siteId', 'logo', 'favicon'],
                    response: ['success', 'data.siteId', 'data.logoUrl', 'data.faviconUrl'],
                },
            ],
        },
        {
            id: 'menu',
            title: 'MENU PIPELINE',
            color: '#f59e0b',
            nodes: [
                {
                    id: 'menu-template',
                    step: 6,
                    title: 'Load Menu Template',
                    subtitle: 'Read prepared template',
                    description:
                        'Load predefined menu definitions for the selected website type and category.',
                    icon: 'bi bi-menu-button-wide',
                    color: 'orange',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/menu/template',
                    request: ['type', 'category'],
                    response: ['success', 'data.type', 'data.category', 'data.menus'],
                },
                {
                    id: 'menu-translate',
                    step: 7,
                    title: 'Translate Menu',
                    subtitle: 'Resolve localization',
                    description: 'Resolve menu title and path values using the selected locale.',
                    icon: 'bi bi-translate',
                    color: 'orange',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/menu/translate',
                    request: ['menus', 'locale'],
                    response: ['success', 'data.locale', 'data.menus'],
                },
                {
                    id: 'menu-generate',
                    step: 8,
                    title: 'Generate Menu Items',
                    subtitle: 'Prepare menu tree',
                    description:
                        'Transform translated menu templates into MenuItem data including parent relationships.',
                    icon: 'bi bi-list-ul',
                    color: 'orange',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/menu/generate',
                    request: ['siteId', 'menus'],
                    response: ['success', 'data.siteId', 'data.items', 'data.count'],
                },
                {
                    id: 'menu-save',
                    step: 9,
                    title: 'Save Menu',
                    subtitle: 'Persist menu tree',
                    description: 'Create MenuItem records inside a database transaction.',
                    icon: 'bi bi-database-fill',
                    color: 'orange',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/menu/save',
                    request: ['siteId', 'items'],
                    response: ['success', 'data.siteId', 'data.count', 'data.items'],
                },
            ],
        },
        {
            id: 'pages',
            title: 'PAGE PIPELINE',
            color: '#3b82f6',
            nodes: [
                {
                    id: 'public-pages',
                    step: 10,
                    title: 'Create Public Pages',
                    subtitle: 'Generate website pages',
                    description: 'Create public Page records from the translated site menu.',
                    icon: 'bi bi-globe2',
                    color: 'green',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/pages/public',
                    request: ['siteId', 'pages'],
                    response: ['success', 'data.siteId', 'data.count', 'data.pages'],
                },
                {
                    id: 'page-seo',
                    step: 11,
                    title: 'Create Page SEO',
                    subtitle: 'Generate SEO metadata',
                    description:
                        'Create default PageSEO records for every page that does not already have SEO data.',
                    icon: 'bi bi-search',
                    color: 'purple',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/pages/seo',
                    request: ['siteId'],
                    response: ['success', 'data.siteId', 'data.count', 'data.pages'],
                },
            ],
        },
        {
            id: 'finish',
            title: 'FINISH',
            color: '#22c55e',
            nodes: [
                {
                    id: 'complete',
                    step: 12,
                    title: 'Complete Site',
                    subtitle: 'Verify workflow result',
                    description:
                        'Verify the created site, menu, pages and SEO records before finishing the workflow.',
                    icon: 'bi bi-check2-circle',
                    color: 'green',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'POST',
                    api: '/api/admin/sites/complete',
                    request: ['siteId'],
                    response: [
                        'success',
                        'data.siteId',
                        'data.name',
                        'data.domain',
                        'data.status',
                        'data.completed',
                        'data.summary',
                    ],
                },
                {
                    id: 'reload',
                    step: 13,
                    title: 'Reload Site List',
                    subtitle: 'Refresh site manager',
                    description: 'Reload the site list after the workflow completes successfully.',
                    icon: 'bi bi-arrow-repeat',
                    color: 'blue',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                    method: 'GET',
                    api: '/api/admin/sites',
                    request: [],
                    response: ['success', 'items', 'sites', 'pagination'],
                },
                {
                    id: 'end',
                    step: 14,
                    title: 'End',
                    subtitle: 'Workflow completed',
                    description: 'Finish the Create Site workflow.',
                    icon: 'bi bi-flag-fill',
                    color: 'gray',
                    status: 'waiting',
                    runtimeStatus: 'idle',
                },
            ],
        },
    ],

    sidebar: {
        request: [
            'name',
            'domain',
            'type',
            'category',
            'logo',
            'favicon',
            'contactEmail',
            'contactPhone',
            'seoTitle',
            'seoDescription',
            'status',
            'isPublic',
            'publishedAt',
            'workspaceId',
            'locale',
        ],
        response: [
            'siteId',
            'name',
            'domain',
            'type',
            'status',
            'isPublic',
            'menuItems',
            'pages',
            'seoPages',
            'completed',
        ],
        apis: [
            {
                method: 'GET',
                endpoint: '/api/admin/sites',
                color: '#16a34a',
                description: ['Load site list', 'Reload after workflow completion'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/validate',
                color: '#2563eb',
                description: ['Validate Create Site payload'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/check-domain',
                color: '#16a34a',
                description: ['Check domain availability'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/create',
                color: '#2563eb',
                description: ['Create Site record'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/pages/system',
                color: '#2563eb',
                description: ['Create Header', 'Create Footer', 'Create 404'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/assets',
                color: '#9333ea',
                description: ['Upload logo', 'Upload favicon'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/menu/template',
                color: '#ea580c',
                description: ['Load MenuTemplate'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/menu/translate',
                color: '#ea580c',
                description: ['Resolve localized menu values'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/menu/generate',
                color: '#ea580c',
                description: ['Generate MenuItem input'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/menu/save',
                color: '#ea580c',
                description: ['Save MenuItem records'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/pages/public',
                color: '#16a34a',
                description: ['Create public pages'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/pages/seo',
                color: '#7c3aed',
                description: ['Create PageSEO records'],
            },
            {
                method: 'POST',
                endpoint: '/api/admin/sites/complete',
                color: '#16a34a',
                description: ['Verify workflow result', 'Complete site creation'],
            },
        ],
    },

    benefits: [
        {
            id: 'automation',
            icon: 'bi bi-shield-check',
            title: 'Tự động hóa hoàn toàn',
            description: 'Toàn bộ quy trình tạo Site được thực hiện theo từng giai đoạn rõ ràng.',
        },
        {
            id: 'database',
            icon: 'bi bi-database-check',
            title: 'Dữ liệu có kiểm soát',
            description: 'Menu, Page và SEO được tạo theo từng stage để dễ kiểm tra và xử lý lỗi.',
        },
        {
            id: 'tracking',
            icon: 'bi bi-activity',
            title: 'Theo dõi realtime',
            description: 'Có thể theo dõi node đang chạy, thời gian xử lý và trạng thái từng bước.',
        },
        {
            id: 'error',
            icon: 'bi bi-exclamation-triangle',
            title: 'Xử lý lỗi rõ ràng',
            description: 'Workflow dừng ngay tại stage lỗi và hiển thị thông tin chi tiết.',
        },
        {
            id: 'experience',
            icon: 'bi bi-arrow-repeat',
            title: 'Đồng bộ Site Manager',
            description: 'Danh sách Site được reload sau khi toàn bộ workflow hoàn tất.',
        },
    ],

    runtime: {
        status: 'idle',
        completedSteps: 0,
        totalSteps: 14,
    },
};
