import type { InternalPage, SiteKind, TemplateAllowed } from "@/components/admin/builder/menus/state/useMenuStore";

/* =========================================================
 * INTERNAL PAGES
 * ======================================================= */

export const LANDING_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "about", path: "/about", label: "About", icon: "bi-info-circle" },
  { id: "features", path: "/features", label: "Features", icon: "bi-grid" },
  { id: "howItWorks", path: "/how-it-works", label: "How It Works", icon: "bi-diagram-3" },
  { id: "solutions", path: "/solutions", label: "Solutions", icon: "bi-puzzle" },
  { id: "integrations", path: "/integrations", label: "Integrations", icon: "bi-plug" },
  { id: "security", path: "/security", label: "Security", icon: "bi-shield-lock" },
  { id: "customers", path: "/customers", label: "Customers", icon: "bi-people" },
  { id: "testimonials", path: "/testimonials", label: "Testimonials", icon: "bi-chat-quote" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies", icon: "bi-journal-richtext" },
  { id: "pricing", path: "/pricing", label: "Pricing", icon: "bi-tags" },
  { id: "demo", path: "/demo", label: "Book a Demo", icon: "bi-calendar-check" },
  { id: "getStarted", path: "/get-started", label: "Get Started", icon: "bi-rocket-takeoff" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "resources", path: "/resources", label: "Resources", icon: "bi-folder" },
  { id: "guides", path: "/guides", label: "Guides", icon: "bi-book" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "docs", path: "/docs", label: "Documentation", icon: "bi-file-earmark-text" },
  { id: "support", path: "/support", label: "Support", icon: "bi-life-preserver" },
  { id: "status", path: "/status", label: "System Status", icon: "bi-activity" },
  { id: "careers", path: "/careers", label: "Careers", icon: "bi-briefcase" },
  { id: "press", path: "/press", label: "Press", icon: "bi-newspaper" },
  { id: "partners", path: "/partners", label: "Partners", icon: "bi-handshake" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const BLOG_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "categories", path: "/categories", label: "Categories", icon: "bi-grid" },
  { id: "tags", path: "/tags", label: "Tags", icon: "bi-tags" },
  { id: "latestPosts", path: "/latest-posts", label: "Latest Posts", icon: "bi-clock-history" },
  { id: "popularPosts", path: "/popular-posts", label: "Popular Posts", icon: "bi-fire" },
  { id: "featuredPosts", path: "/featured-posts", label: "Featured Posts", icon: "bi-star" },
  { id: "trending", path: "/trending", label: "Trending", icon: "bi-graph-up-arrow" },
  { id: "editorsPick", path: "/editors-pick", label: "Editor's Pick", icon: "bi-hand-thumbs-up" },
  { id: "mostViewed", path: "/most-viewed", label: "Most Viewed", icon: "bi-eye" },
  { id: "series", path: "/series", label: "Series", icon: "bi-collection" },
  { id: "guides", path: "/guides", label: "Guides", icon: "bi-book" },
  { id: "tutorials", path: "/tutorials", label: "Tutorials", icon: "bi-mortarboard" },
  { id: "news", path: "/news", label: "News", icon: "bi-newspaper" },
  { id: "reviews", path: "/reviews", label: "Reviews", icon: "bi-star-half" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies", icon: "bi-journal-richtext" },
  { id: "authors", path: "/authors", label: "Authors", icon: "bi-people" },
  { id: "topAuthors", path: "/top-authors", label: "Top Authors", icon: "bi-award" },
  { id: "authorProfile", path: "/authors/:id", label: "Author Profile", icon: "bi-person-badge" },
  { id: "community", path: "/community", label: "Community", icon: "bi-people-fill" },
  { id: "search", path: "/search", label: "Search", icon: "bi-search" },
  { id: "newsletter", path: "/newsletter", label: "Newsletter", icon: "bi-envelope-paper" },
  { id: "bookmarks", path: "/bookmarks", label: "Bookmarks", icon: "bi-bookmark" },
  { id: "readingList", path: "/reading-list", label: "Reading List", icon: "bi-list-check" },
  { id: "login", path: "/login", label: "Login", icon: "bi-box-arrow-in-right" },
  { id: "register", path: "/register", label: "Register", icon: "bi-person-plus" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard", icon: "bi-speedometer2" },
  { id: "settings", path: "/settings", label: "Settings", icon: "bi-gear" },
  { id: "about", path: "/about", label: "About", icon: "bi-info-circle" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "careers", path: "/careers", label: "Careers", icon: "bi-briefcase" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const COMPANY_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "about", path: "/about", label: "About Us", icon: "bi-info-circle" },
  { id: "services", path: "/services", label: "Services", icon: "bi-briefcase" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "ourStory", path: "/our-story", label: "Our Story", icon: "bi-book" },
  { id: "missionVision", path: "/mission-vision", label: "Mission & Vision", icon: "bi-bullseye" },
  { id: "leadership", path: "/leadership", label: "Leadership", icon: "bi-person-workspace" },
  { id: "team", path: "/team", label: "Our Team", icon: "bi-people" },
  { id: "careers", path: "/careers", label: "Careers", icon: "bi-briefcase" },
  { id: "solutions", path: "/solutions", label: "Solutions", icon: "bi-puzzle" },
  { id: "industries", path: "/industries", label: "Industries", icon: "bi-building" },
  { id: "pricing", path: "/pricing", label: "Pricing", icon: "bi-tags" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies", icon: "bi-journal-richtext" },
  { id: "portfolio", path: "/portfolio", label: "Portfolio", icon: "bi-collection" },
  { id: "clients", path: "/clients", label: "Clients", icon: "bi-people-fill" },
  { id: "testimonials", path: "/testimonials", label: "Testimonials", icon: "bi-chat-quote" },
  { id: "partners", path: "/partners", label: "Partners", icon: "bi-handshake" },
  { id: "awards", path: "/awards", label: "Awards & Recognition", icon: "bi-trophy" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "news", path: "/news", label: "News", icon: "bi-newspaper" },
  { id: "events", path: "/events", label: "Events", icon: "bi-calendar-event" },
  { id: "resources", path: "/resources", label: "Resources", icon: "bi-folder" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "support", path: "/support", label: "Support", icon: "bi-life-preserver" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const BOOKING_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "rooms", path: "/rooms", label: "Rooms", icon: "bi-door-open" },
  { id: "booking", path: "/booking", label: "Booking", icon: "bi-calendar-check" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "roomDetails", path: "/rooms/:id", label: "Room Details", icon: "bi-house-door" },
  { id: "availability", path: "/availability", label: "Check Availability", icon: "bi-search" },
  { id: "offers", path: "/offers", label: "Special Offers", icon: "bi-tags" },
  { id: "packages", path: "/packages", label: "Packages", icon: "bi-box-seam" },
  { id: "amenities", path: "/amenities", label: "Amenities", icon: "bi-stars" },
  { id: "services", path: "/services", label: "Services", icon: "bi-cone-striped" },
  { id: "spa", path: "/spa", label: "Spa & Wellness", icon: "bi-flower1" },
  { id: "restaurant", path: "/restaurant", label: "Restaurant & Dining", icon: "bi-cup-hot" },
  { id: "activities", path: "/activities", label: "Activities", icon: "bi-bicycle" },
  { id: "cart", path: "/cart", label: "Cart", icon: "bi-cart" },
  { id: "checkout", path: "/checkout", label: "Checkout", icon: "bi-credit-card" },
  { id: "confirmation", path: "/confirmation", label: "Booking Confirmation", icon: "bi-patch-check" },
  { id: "account", path: "/account", label: "My Account", icon: "bi-person" },
  { id: "reservations", path: "/reservations", label: "My Reservations", icon: "bi-journal-check" },
  { id: "about", path: "/about", label: "About Us", icon: "bi-info-circle" },
  { id: "gallery", path: "/gallery", label: "Gallery", icon: "bi-images" },
  { id: "reviews", path: "/reviews", label: "Guest Reviews", icon: "bi-chat-quote" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms & Conditions", icon: "bi-file-earmark-lock" },
];

export const NEWS_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "latest", path: "/latest", label: "Latest News", icon: "bi-clock-history" },
  { id: "breaking", path: "/breaking", label: "Breaking News", icon: "bi-lightning-charge" },
  { id: "trending", path: "/trending", label: "Trending", icon: "bi-graph-up-arrow" },
  { id: "world", path: "/world", label: "World", icon: "bi-globe" },
  { id: "business", path: "/business", label: "Business", icon: "bi-briefcase" },
  { id: "technology", path: "/technology", label: "Technology", icon: "bi-cpu" },
  { id: "science", path: "/science", label: "Science", icon: "bi-beaker" },
  { id: "health", path: "/health", label: "Health", icon: "bi-heart-pulse" },
  { id: "sports", path: "/sports", label: "Sports", icon: "bi-trophy" },
  { id: "entertainment", path: "/entertainment", label: "Entertainment", icon: "bi-film" },
  { id: "lifestyle", path: "/lifestyle", label: "Lifestyle", icon: "bi-sun" },
  { id: "videos", path: "/videos", label: "Videos", icon: "bi-play-btn" },
  { id: "podcasts", path: "/podcasts", label: "Podcasts", icon: "bi-mic" },
  { id: "photoGallery", path: "/gallery", label: "Photo Gallery", icon: "bi-images" },
  { id: "opinions", path: "/opinions", label: "Opinions", icon: "bi-chat-left-text" },
  { id: "editorial", path: "/editorial", label: "Editorial", icon: "bi-pencil-square" },
  { id: "features", path: "/features", label: "Features", icon: "bi-grid" },
  { id: "investigations", path: "/investigations", label: "Investigations", icon: "bi-search" },
  { id: "search", path: "/search", label: "Search", icon: "bi-search-heart" },
  { id: "newsletter", path: "/newsletter", label: "Newsletter", icon: "bi-envelope-paper" },
  { id: "about", path: "/about", label: "About Us", icon: "bi-info-circle" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const LMS_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "courses", path: "/courses", label: "Courses", icon: "bi-book" },
  { id: "myLearning", path: "/my-learning", label: "My Learning", icon: "bi-journal-check" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "categories", path: "/categories", label: "Categories", icon: "bi-grid" },
  { id: "search", path: "/search", label: "Search", icon: "bi-search" },
  { id: "featured", path: "/featured", label: "Featured Courses", icon: "bi-star" },
  { id: "popular", path: "/popular", label: "Popular Courses", icon: "bi-fire" },
  { id: "newCourses", path: "/new-courses", label: "New Courses", icon: "bi-lightning" },
  { id: "courseDetails", path: "/courses/:id", label: "Course Details", icon: "bi-file-earmark-text" },
  { id: "lesson", path: "/lesson/:id", label: "Lesson", icon: "bi-play-circle" },
  { id: "quiz", path: "/quiz/:id", label: "Quiz", icon: "bi-patch-question" },
  { id: "certificates", path: "/certificates", label: "Certificates", icon: "bi-award" },
  { id: "instructors", path: "/instructors", label: "Instructors", icon: "bi-person-video3" },
  { id: "becomeInstructor", path: "/become-instructor", label: "Become an Instructor", icon: "bi-person-plus" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard", icon: "bi-speedometer2" },
  { id: "profile", path: "/profile", label: "Profile", icon: "bi-person" },
  { id: "settings", path: "/settings", label: "Settings", icon: "bi-gear" },
  { id: "wishlist", path: "/wishlist", label: "Wishlist", icon: "bi-heart" },
  { id: "pricing", path: "/pricing", label: "Pricing", icon: "bi-tags" },
  { id: "cart", path: "/cart", label: "Cart", icon: "bi-cart" },
  { id: "checkout", path: "/checkout", label: "Checkout", icon: "bi-credit-card" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const DIRECTORY_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "listings", path: "/listings", label: "Listings", icon: "bi-card-list" },
  { id: "categories", path: "/categories", label: "Categories", icon: "bi-grid" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "search", path: "/search", label: "Search", icon: "bi-search" },
  { id: "locations", path: "/locations", label: "Locations", icon: "bi-geo-alt" },
  { id: "nearby", path: "/nearby", label: "Nearby", icon: "bi-compass" },
  { id: "featured", path: "/featured", label: "Featured Listings", icon: "bi-star" },
  { id: "popular", path: "/popular", label: "Popular Listings", icon: "bi-fire" },
  { id: "topRated", path: "/top-rated", label: "Top Rated", icon: "bi-trophy" },
  { id: "listingDetails", path: "/listings/:id", label: "Listing Details", icon: "bi-file-earmark-text" },
  { id: "addListing", path: "/add-listing", label: "Add Listing", icon: "bi-plus-square" },
  { id: "editListing", path: "/edit-listing", label: "Edit Listing", icon: "bi-pencil-square" },
  { id: "reviews", path: "/reviews", label: "Reviews", icon: "bi-chat-quote" },
  { id: "writeReview", path: "/write-review", label: "Write a Review", icon: "bi-pencil" },
  { id: "account", path: "/account", label: "My Account", icon: "bi-person" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard", icon: "bi-speedometer2" },
  { id: "bookmarks", path: "/bookmarks", label: "Bookmarks", icon: "bi-bookmark" },
  { id: "messages", path: "/messages", label: "Messages", icon: "bi-chat-dots" },
  { id: "pricing", path: "/pricing", label: "Pricing", icon: "bi-tags" },
  { id: "plans", path: "/plans", label: "Plans", icon: "bi-kanban" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "about", path: "/about", label: "About Us", icon: "bi-info-circle" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-check" },
  { id: "terms", path: "/terms", label: "Terms of Service", icon: "bi-file-earmark-lock" },
];

export const ECOMMERCE_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home", icon: "bi-house" },
  { id: "shop", path: "/shop", label: "Shop", icon: "bi-shop" },
  { id: "products", path: "/products", label: "Products", icon: "bi-box-seam" },
  { id: "categories", path: "/categories", label: "Categories", icon: "bi-grid" },
  { id: "collections", path: "/collections", label: "Collections", icon: "bi-collection" },
  { id: "brands", path: "/brands", label: "Brands", icon: "bi-award" },
  { id: "featured", path: "/featured", label: "Featured", icon: "bi-star" },
  { id: "trending", path: "/trending", label: "Trending", icon: "bi-graph-up" },
  { id: "newArrivals", path: "/new-arrivals", label: "New Arrivals", icon: "bi-lightning" },
  { id: "bestSellers", path: "/best-sellers", label: "Best Sellers", icon: "bi-trophy" },
  { id: "flashSale", path: "/flash-sale", label: "Flash Sale", icon: "bi-lightning-charge" },
  { id: "deals", path: "/deals", label: "Deals", icon: "bi-tags" },
  { id: "offers", path: "/offers", label: "Offers", icon: "bi-percent" },
  { id: "coupons", path: "/coupons", label: "Coupons", icon: "bi-ticket" },
  { id: "giftCards", path: "/gift-cards", label: "Gift Cards", icon: "bi-gift" },
  { id: "wishlist", path: "/wishlist", label: "Wishlist", icon: "bi-heart" },
  { id: "cart", path: "/cart", label: "Cart", icon: "bi-cart" },
  { id: "checkout", path: "/checkout", label: "Checkout", icon: "bi-credit-card" },
  { id: "account", path: "/account", label: "My Account", icon: "bi-person" },
  { id: "orders", path: "/orders", label: "My Orders", icon: "bi-receipt" },
  { id: "orderTracking", path: "/order-tracking", label: "Order Tracking", icon: "bi-truck" },
  { id: "addresses", path: "/addresses", label: "Addresses", icon: "bi-geo-alt" },
  { id: "about", path: "/about", label: "About Us", icon: "bi-info-circle" },
  { id: "contact", path: "/contact", label: "Contact", icon: "bi-envelope" },
  { id: "faq", path: "/faq", label: "FAQ", icon: "bi-question-circle" },
  { id: "blog", path: "/blog", label: "Blog", icon: "bi-journal-text" },
  { id: "shippingInfo", path: "/shipping-info", label: "Shipping Info", icon: "bi-box" },
  { id: "returnPolicy", path: "/return-policy", label: "Return Policy", icon: "bi-arrow-return-left" },
  { id: "sizeGuide", path: "/size-guide", label: "Size Guide", icon: "bi-rulers" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy", icon: "bi-shield-lock" },
  { id: "terms", path: "/terms", label: "Terms & Conditions", icon: "bi-file-earmark-text" },
];

/* =========================================================
 * HEADER BASIC
 * ======================================================= */

export const LANDING_HEADER_BASIC = [
  "Home",
  "About",
  "Features",
  "How It Works",
  "Solutions",
  "Integrations",
  "Security",
  "Customers",
  "Testimonials",
  "Case Studies",
  "Pricing",
  "Book a Demo",
  "Get Started",
  "Blog",
  "Resources",
  "Guides",
  "FAQ",
  "Documentation",
  "Support",
  "System Status",
  "Careers",
  "Press",
  "Partners",
  "Contact",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const BLOG_HEADER_BASIC = [
  "Home",
  "Blog",
  "Categories",
  "Tags",
  "Latest Posts",
  "Popular Posts",
  "Featured Posts",
  "Trending",
  "Editor's Pick",
  "Most Viewed",
  "Series",
  "Guides",
  "Tutorials",
  "News",
  "Reviews",
  "Case Studies",
  "Authors",
  "Top Authors",
  "Author Profile",
  "Community",
  "Search",
  "Newsletter",
  "Bookmarks",
  "Reading List",
  "Login",
  "Register",
  "Dashboard",
  "Settings",
  "About",
  "Contact",
  "FAQ",
  "Careers",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const COMPANY_HEADER_BASIC = [
  "Home",
  "About Us",
  "Services",
  "Contact",
  "Our Story",
  "Mission & Vision",
  "Leadership",
  "Our Team",
  "Careers",
  "Solutions",
  "Industries",
  "Pricing",
  "Case Studies",
  "Portfolio",
  "Clients",
  "Testimonials",
  "Partners",
  "Awards & Recognition",
  "Blog",
  "News",
  "Events",
  "Resources",
  "FAQ",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const BOOKING_HEADER_BASIC = [
  "Home",
  "Rooms",
  "Booking",
  "Contact",
  "Room Details",
  "Check Availability",
  "Special Offers",
  "Packages",
  "Amenities",
  "Services",
  "Spa & Wellness",
  "Restaurant & Dining",
  "Activities",
  "Cart",
  "Checkout",
  "Booking Confirmation",
  "My Account",
  "My Reservations",
  "About Us",
  "Gallery",
  "Guest Reviews",
  "Blog",
  "FAQ",
  "Privacy Policy",
  "Terms & Conditions",
] as const;

export const NEWS_HEADER_BASIC = [
  "Home",
  "Latest News",
  "Breaking News",
  "Trending",
  "World",
  "Business",
  "Technology",
  "Science",
  "Health",
  "Sports",
  "Entertainment",
  "Lifestyle",
  "Videos",
  "Podcasts",
  "Photo Gallery",
  "Opinions",
  "Editorial",
  "Features",
  "Investigations",
  "Search",
  "Newsletter",
  "About Us",
  "Contact",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const LMS_HEADER_BASIC = [
  "Home",
  "Courses",
  "My Learning",
  "Contact",
  "Categories",
  "Search",
  "Featured Courses",
  "Popular Courses",
  "New Courses",
  "Course Details",
  "Lesson",
  "Quiz",
  "Certificates",
  "Instructors",
  "Become an Instructor",
  "Dashboard",
  "Profile",
  "Settings",
  "Wishlist",
  "Pricing",
  "Cart",
  "Checkout",
  "Blog",
  "FAQ",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const DIRECTORY_HEADER_BASIC = [
  "Home",
  "Listings",
  "Categories",
  "Contact",
  "Search",
  "Locations",
  "Nearby",
  "Featured Listings",
  "Popular Listings",
  "Top Rated",
  "Listing Details",
  "Add Listing",
  "Edit Listing",
  "Reviews",
  "Write a Review",
  "My Account",
  "Dashboard",
  "Bookmarks",
  "Messages",
  "Pricing",
  "Plans",
  "Blog",
  "FAQ",
  "About Us",
  "Privacy Policy",
  "Terms of Service",
] as const;

export const ECOMMERCE_HEADER_FULL = [
  "Home",
  "Shop",
  "Products",
  "Categories",
  "Collections",
  "Brands",
  "New Arrivals",
  "Best Sellers",
  "Featured",
  "Trending",
  "Flash Sale",
  "Deals",
  "Offers",
  "Coupons",
  "Gift Cards",
  "Wishlist",
  "Cart",
  "Checkout",
  "My Account",
  "My Orders",
  "Order Tracking",
  "Addresses",
  "About Us",
  "Contact",
  "FAQ",
  "Blog",
  "Shipping Info",
  "Return Policy",
  "Size Guide",
  "Privacy Policy",
  "Terms & Conditions",
] as const;

/* =========================================================
 * MAPS
 * ======================================================= */

export const INTERNAL_PAGE_SETS: Record<SiteKind, InternalPage[]> = {
  landing: LANDING_INTERNAL_PAGES,
  blog: BLOG_INTERNAL_PAGES,
  company: COMPANY_INTERNAL_PAGES,
  ecommerce: ECOMMERCE_INTERNAL_PAGES,
  booking: BOOKING_INTERNAL_PAGES,
  news: NEWS_INTERNAL_PAGES,
  lms: LMS_INTERNAL_PAGES,
  directory: DIRECTORY_INTERNAL_PAGES,
};

export const TEMPLATE_ALLOWED_BY_SITE: Record<SiteKind, TemplateAllowed> = {
  landing: { header: { home: [...LANDING_HEADER_BASIC] } },
  blog: { header: { home: [...BLOG_HEADER_BASIC] } },
  company: { header: { home: [...COMPANY_HEADER_BASIC] } },
  ecommerce: {
    header: {
      home: [...ECOMMERCE_HEADER_FULL],
    },
  },
  booking: { header: { home: [...BOOKING_HEADER_BASIC] } },
  news: { header: { home: [...NEWS_HEADER_BASIC] } },
  lms: { header: { home: [...LMS_HEADER_BASIC] } },
  directory: { header: { home: [...DIRECTORY_HEADER_BASIC] } },
};