import type { InternalPage, SiteKind, TemplateAllowed } from "@/components/admin/builder/menus/state/useMenuStore";

/* =========================================================
 * INTERNAL PAGES
 * ======================================================= */

export const LANDING_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "about", path: "/about", label: "About" },
  { id: "features", path: "/features", label: "Features" },
  { id: "howItWorks", path: "/how-it-works", label: "How It Works" },
  { id: "solutions", path: "/solutions", label: "Solutions" },
  { id: "integrations", path: "/integrations", label: "Integrations" },
  { id: "security", path: "/security", label: "Security" },
  { id: "customers", path: "/customers", label: "Customers" },
  { id: "testimonials", path: "/testimonials", label: "Testimonials" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies" },
  { id: "pricing", path: "/pricing", label: "Pricing" },
  { id: "demo", path: "/demo", label: "Book a Demo" },
  { id: "getStarted", path: "/get-started", label: "Get Started" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "resources", path: "/resources", label: "Resources" },
  { id: "guides", path: "/guides", label: "Guides" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "docs", path: "/docs", label: "Documentation" },
  { id: "support", path: "/support", label: "Support" },
  { id: "status", path: "/status", label: "System Status" },
  { id: "careers", path: "/careers", label: "Careers" },
  { id: "press", path: "/press", label: "Press" },
  { id: "partners", path: "/partners", label: "Partners" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];

export const BLOG_INTERNAL_PAGES: InternalPage[] = [
  // Core
  { id: "home", path: "/", label: "Home" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "categories", path: "/categories", label: "Categories" },
  { id: "tags", path: "/tags", label: "Tags" },
  { id: "latestPosts", path: "/latest-posts", label: "Latest Posts" },
  { id: "popularPosts", path: "/popular-posts", label: "Popular Posts" },
  { id: "featuredPosts", path: "/featured-posts", label: "Featured Posts" },
  { id: "trending", path: "/trending", label: "Trending" },
  { id: "editorsPick", path: "/editors-pick", label: "Editor's Pick" },
  { id: "mostViewed", path: "/most-viewed", label: "Most Viewed" },
  { id: "series", path: "/series", label: "Series" },
  { id: "guides", path: "/guides", label: "Guides" },
  { id: "tutorials", path: "/tutorials", label: "Tutorials" },
  { id: "news", path: "/news", label: "News" },
  { id: "reviews", path: "/reviews", label: "Reviews" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies" },
  { id: "authors", path: "/authors", label: "Authors" },
  { id: "topAuthors", path: "/top-authors", label: "Top Authors" },
  { id: "authorProfile", path: "/authors/:id", label: "Author Profile" },
  { id: "community", path: "/community", label: "Community" },
  { id: "search", path: "/search", label: "Search" },
  { id: "newsletter", path: "/newsletter", label: "Newsletter" },
  { id: "bookmarks", path: "/bookmarks", label: "Bookmarks" },
  { id: "readingList", path: "/reading-list", label: "Reading List" },
  { id: "login", path: "/login", label: "Login" },
  { id: "register", path: "/register", label: "Register" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard" },
  { id: "settings", path: "/settings", label: "Settings" },
  { id: "about", path: "/about", label: "About" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "careers", path: "/careers", label: "Careers" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];
export const COMPANY_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "about", path: "/about", label: "About Us" },
  { id: "services", path: "/services", label: "Services" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "ourStory", path: "/our-story", label: "Our Story" },
  { id: "missionVision", path: "/mission-vision", label: "Mission & Vision" },
  { id: "leadership", path: "/leadership", label: "Leadership" },
  { id: "team", path: "/team", label: "Our Team" },
  { id: "careers", path: "/careers", label: "Careers" },
  { id: "solutions", path: "/solutions", label: "Solutions" },
  { id: "industries", path: "/industries", label: "Industries" },
  { id: "pricing", path: "/pricing", label: "Pricing" },
  { id: "caseStudies", path: "/case-studies", label: "Case Studies" },
  { id: "portfolio", path: "/portfolio", label: "Portfolio" },
  { id: "clients", path: "/clients", label: "Clients" },
  { id: "testimonials", path: "/testimonials", label: "Testimonials" },
  { id: "partners", path: "/partners", label: "Partners" },
  { id: "awards", path: "/awards", label: "Awards & Recognition" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "news", path: "/news", label: "News" },
  { id: "events", path: "/events", label: "Events" },
  { id: "resources", path: "/resources", label: "Resources" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "support", path: "/support", label: "Support" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];

export const BOOKING_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "rooms", path: "/rooms", label: "Rooms" },
  { id: "booking", path: "/booking", label: "Booking" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "roomDetails", path: "/rooms/:id", label: "Room Details" },
  { id: "availability", path: "/availability", label: "Check Availability" },
  { id: "offers", path: "/offers", label: "Special Offers" },
  { id: "packages", path: "/packages", label: "Packages" },
  { id: "amenities", path: "/amenities", label: "Amenities" },
  { id: "services", path: "/services", label: "Services" },
  { id: "spa", path: "/spa", label: "Spa & Wellness" },
  { id: "restaurant", path: "/restaurant", label: "Restaurant & Dining" },
  { id: "activities", path: "/activities", label: "Activities" },
  { id: "cart", path: "/cart", label: "Cart" },
  { id: "checkout", path: "/checkout", label: "Checkout" },
  { id: "confirmation", path: "/confirmation", label: "Booking Confirmation" },
  { id: "account", path: "/account", label: "My Account" },
  { id: "reservations", path: "/reservations", label: "My Reservations" },
  { id: "about", path: "/about", label: "About Us" },
  { id: "gallery", path: "/gallery", label: "Gallery" },
  { id: "reviews", path: "/reviews", label: "Guest Reviews" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms & Conditions" },
];

export const NEWS_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "latest", path: "/latest", label: "Latest News" },
  { id: "breaking", path: "/breaking", label: "Breaking News" },
  { id: "trending", path: "/trending", label: "Trending" },
  { id: "world", path: "/world", label: "World" },
  { id: "business", path: "/business", label: "Business" },
  { id: "technology", path: "/technology", label: "Technology" },
  { id: "science", path: "/science", label: "Science" },
  { id: "health", path: "/health", label: "Health" },
  { id: "sports", path: "/sports", label: "Sports" },
  { id: "entertainment", path: "/entertainment", label: "Entertainment" },
  { id: "lifestyle", path: "/lifestyle", label: "Lifestyle" },
  { id: "videos", path: "/videos", label: "Videos" },
  { id: "podcasts", path: "/podcasts", label: "Podcasts" },
  { id: "photoGallery", path: "/gallery", label: "Photo Gallery" },
  { id: "opinions", path: "/opinions", label: "Opinions" },
  { id: "editorial", path: "/editorial", label: "Editorial" },
  { id: "features", path: "/features", label: "Features" },
  { id: "investigations", path: "/investigations", label: "Investigations" },
  { id: "search", path: "/search", label: "Search" },
  { id: "newsletter", path: "/newsletter", label: "Newsletter" },
  { id: "about", path: "/about", label: "About Us" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];

export const LMS_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "courses", path: "/courses", label: "Courses" },
  { id: "myLearning", path: "/my-learning", label: "My Learning" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "categories", path: "/categories", label: "Categories" },
  { id: "search", path: "/search", label: "Search" },
  { id: "featured", path: "/featured", label: "Featured Courses" },
  { id: "popular", path: "/popular", label: "Popular Courses" },
  { id: "newCourses", path: "/new-courses", label: "New Courses" },
  { id: "courseDetails", path: "/courses/:id", label: "Course Details" },
  { id: "lesson", path: "/lesson/:id", label: "Lesson" },
  { id: "quiz", path: "/quiz/:id", label: "Quiz" },
  { id: "certificates", path: "/certificates", label: "Certificates" },
  { id: "instructors", path: "/instructors", label: "Instructors" },
  { id: "becomeInstructor", path: "/become-instructor", label: "Become an Instructor" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard" },
  { id: "profile", path: "/profile", label: "Profile" },
  { id: "settings", path: "/settings", label: "Settings" },
  { id: "wishlist", path: "/wishlist", label: "Wishlist" },
  { id: "pricing", path: "/pricing", label: "Pricing" },
  { id: "cart", path: "/cart", label: "Cart" },
  { id: "checkout", path: "/checkout", label: "Checkout" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];

export const DIRECTORY_INTERNAL_PAGES: InternalPage[] = [
  { id: "home", path: "/", label: "Home" },
  { id: "listings", path: "/listings", label: "Listings" },
  { id: "categories", path: "/categories", label: "Categories" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "search", path: "/search", label: "Search" },
  { id: "locations", path: "/locations", label: "Locations" },
  { id: "nearby", path: "/nearby", label: "Nearby" },
  { id: "featured", path: "/featured", label: "Featured Listings" },
  { id: "popular", path: "/popular", label: "Popular Listings" },
  { id: "topRated", path: "/top-rated", label: "Top Rated" },
  { id: "listingDetails", path: "/listings/:id", label: "Listing Details" },
  { id: "addListing", path: "/add-listing", label: "Add Listing" },
  { id: "editListing", path: "/edit-listing", label: "Edit Listing" },
  { id: "reviews", path: "/reviews", label: "Reviews" },
  { id: "writeReview", path: "/write-review", label: "Write a Review" },
  { id: "account", path: "/account", label: "My Account" },
  { id: "dashboard", path: "/dashboard", label: "Dashboard" },
  { id: "bookmarks", path: "/bookmarks", label: "Bookmarks" },
  { id: "messages", path: "/messages", label: "Messages" },
  { id: "pricing", path: "/pricing", label: "Pricing" },
  { id: "plans", path: "/plans", label: "Plans" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "about", path: "/about", label: "About Us" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms of Service" },
];

export const ECOMMERCE_INTERNAL_PAGES: InternalPage[] = [
  // Main
  { id: "home", path: "/", label: "Home" },
  { id: "shop", path: "/shop", label: "Shop" },
  { id: "products", path: "/products", label: "Products" },
  { id: "categories", path: "/categories", label: "Categories" },
  { id: "collections", path: "/collections", label: "Collections" },
  { id: "brands", path: "/brands", label: "Brands" },
  { id: "featured", path: "/featured", label: "Featured" },
  { id: "trending", path: "/trending", label: "Trending" },
  { id: "newArrivals", path: "/new-arrivals", label: "New Arrivals" },
  { id: "bestSellers", path: "/best-sellers", label: "Best Sellers" },
  { id: "flashSale", path: "/flash-sale", label: "Flash Sale" },
  { id: "deals", path: "/deals", label: "Deals" },
  { id: "offers", path: "/offers", label: "Offers" },
  { id: "coupons", path: "/coupons", label: "Coupons" },
  { id: "giftCards", path: "/gift-cards", label: "Gift Cards" },
  { id: "wishlist", path: "/wishlist", label: "Wishlist" },
  { id: "cart", path: "/cart", label: "Cart" },
  { id: "checkout", path: "/checkout", label: "Checkout" },
  { id: "account", path: "/account", label: "My Account" },
  { id: "orders", path: "/orders", label: "My Orders" },
  { id: "orderTracking", path: "/order-tracking", label: "Order Tracking" },
  { id: "addresses", path: "/addresses", label: "Addresses" },
  { id: "about", path: "/about", label: "About Us" },
  { id: "contact", path: "/contact", label: "Contact" },
  { id: "faq", path: "/faq", label: "FAQ" },
  { id: "blog", path: "/blog", label: "Blog" },
  { id: "shippingInfo", path: "/shipping-info", label: "Shipping Info" },
  { id: "returnPolicy", path: "/return-policy", label: "Return Policy" },
  { id: "sizeGuide", path: "/size-guide", label: "Size Guide" },
  { id: "privacyPolicy", path: "/privacy-policy", label: "Privacy Policy" },
  { id: "terms", path: "/terms", label: "Terms & Conditions" },
];

/* =========================================================
 * HEADER BASIC
 * ======================================================= */

export const LANDING_HEADER_BASIC = [
  "Home",
  "About",
  "Features",
  "How It Works",
  "Solutions",
  "Integrations",
  "Security",
  "Customers",
  "Testimonials",
  "Case Studies",
  "Pricing",
  "Book a Demo",
  "Get Started",
  "Blog",
  "Resources",
  "Guides",
  "FAQ",
  "Documentation",
  "Support",
  "System Status",
  "Careers",
  "Press",
  "Partners",
  "Contact",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const BLOG_HEADER_BASIC = [
  "Home",
  "Blog",
  "Categories",
  "Tags",
  "Latest Posts",
  "Popular Posts",
  "Featured Posts",
  "Trending",
  "Editor's Pick",
  "Most Viewed",
  "Series",
  "Guides",
  "Tutorials",
  "News",
  "Reviews",
  "Case Studies",
  "Authors",
  "Top Authors",
  "Author Profile",
  "Community",
  "Search",
  "Newsletter",
  "Bookmarks",
  "Reading List",
  "Login",
  "Register",
  "Dashboard",
  "Settings",
  "About",
  "Contact",
  "FAQ",
  "Careers",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const COMPANY_HEADER_BASIC = [
  "Home",
  "About Us",
  "Services",
  "Contact",
  "Our Story",
  "Mission & Vision",
  "Leadership",
  "Our Team",
  "Careers",
  "Solutions",
  "Industries",
  "Pricing",
  "Case Studies",
  "Portfolio",
  "Clients",
  "Testimonials",
  "Partners",
  "Awards & Recognition",
  "Blog",
  "News",
  "Events",
  "Resources",
  "FAQ",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const BOOKING_HEADER_BASIC = [
  "Home",
  "Rooms",
  "Booking",
  "Contact",
  "Room Details",
  "Check Availability",
  "Special Offers",
  "Packages",
  "Amenities",
  "Services",
  "Spa & Wellness",
  "Restaurant & Dining",
  "Activities",
  "Cart",
  "Checkout",
  "Booking Confirmation",
  "My Account",
  "My Reservations",
  "About Us",
  "Gallery",
  "Guest Reviews",
  "Blog",
  "FAQ",
  "Privacy Policy",
  "Terms & Conditions",
] as const;
export const NEWS_HEADER_BASIC = [
  "Home",
  "Latest News",
  "Breaking News",
  "Trending",
  "World",
  "Business",
  "Technology",
  "Science",
  "Health",
  "Sports",
  "Entertainment",
  "Lifestyle",
  "Videos",
  "Podcasts",
  "Photo Gallery",
  "Opinions",
  "Editorial",
  "Features",
  "Investigations",
  "Search",
  "Newsletter",
  "About Us",
  "Contact",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const LMS_HEADER_BASIC = [
  "Home",
  "Courses",
  "My Learning",
  "Contact",
  "Categories",
  "Search",
  "Featured Courses",
  "Popular Courses",
  "New Courses",
  "Course Details",
  "Lesson",
  "Quiz",
  "Certificates",
  "Instructors",
  "Become an Instructor",
  "Dashboard",
  "Profile",
  "Settings",
  "Wishlist",
  "Pricing",
  "Cart",
  "Checkout",
  "Blog",
  "FAQ",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const DIRECTORY_HEADER_BASIC = [
  "Home",
  "Listings",
  "Categories",
  "Contact",
  "Search",
  "Locations",
  "Nearby",
  "Featured Listings",
  "Popular Listings",
  "Top Rated",
  "Listing Details",
  "Add Listing",
  "Edit Listing",
  "Reviews",
  "Write a Review",
  "My Account",
  "Dashboard",
  "Bookmarks",
  "Messages",
  "Pricing",
  "Plans",
  "Blog",
  "FAQ",
  "About Us",
  "Privacy Policy",
  "Terms of Service",
] as const;
export const ECOMMERCE_HEADER_FULL = [
  "Home",
  "Shop",
  "Products",
  "Categories",
  "Collections",
  "Brands",
  "New Arrivals",
  "Best Sellers",
  "Featured",
  "Trending",
  "Flash Sale",
  "Deals",
  "Offers",
  "Coupons",
  "Gift Cards",
  "Wishlist",
  "Cart",
  "Checkout",
  "My Account",
  "My Orders",
  "Order Tracking",
  "Addresses",
  "About Us",
  "Contact",
  "FAQ",
  "Blog",
  "Shipping Info",
  "Return Policy",
  "Size Guide",
  "Privacy Policy",
  "Terms & Conditions",
] as const;

/* =========================================================
 * MAPS
 * ======================================================= */

export const INTERNAL_PAGE_SETS: Record<SiteKind, InternalPage[]> = {
  landing: LANDING_INTERNAL_PAGES,
  blog: BLOG_INTERNAL_PAGES,
  company: COMPANY_INTERNAL_PAGES,
  ecommerce: ECOMMERCE_INTERNAL_PAGES,
  booking: BOOKING_INTERNAL_PAGES,
  news: NEWS_INTERNAL_PAGES,
  lms: LMS_INTERNAL_PAGES,
  directory: DIRECTORY_INTERNAL_PAGES,
};

export const TEMPLATE_ALLOWED_BY_SITE: Record<SiteKind, TemplateAllowed> = {
  landing: { header: { home: [...LANDING_HEADER_BASIC] } },
  blog: { header: { home: [...BLOG_HEADER_BASIC] } },
  company: { header: { home: [...COMPANY_HEADER_BASIC] } },
  ecommerce: {
    header: {
      home: [...ECOMMERCE_HEADER_FULL],
    },
  },
  booking: { header: { home: [...BOOKING_HEADER_BASIC] } },
  news: { header: { home: [...NEWS_HEADER_BASIC] } },
  lms: { header: { home: [...LMS_HEADER_BASIC] } },
  directory: { header: { home: [...DIRECTORY_HEADER_BASIC] } },
};