-- AlterTable
ALTER TABLE "profiles" ADD COLUMN     "bio" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "company" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "dob_day" INTEGER,
ADD COLUMN     "dob_month" TEXT,
ADD COLUMN     "dob_year" INTEGER,
ADD COLUMN     "facebook" TEXT,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "github" TEXT,
ADD COLUMN     "hire_date" TIMESTAMP(3),
ADD COLUMN     "job_title" TEXT,
ADD COLUMN     "linkedin" TEXT,
ADD COLUMN     "locale" TEXT,
ADD COLUMN     "manager" TEXT,
ADD COLUMN     "slogan" TEXT,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "twitter" TEXT,
ADD COLUMN     "two_fa" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "website" TEXT;
